" Plug Extensions
call plug#begin(expand('<sfile>:p:h').'/plugged')
Plug 'morhetz/gruvbox'
Plug 'preservim/nerdtree'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'christoomey/vim-tmux-navigator'
Plug 'neovimhaskell/haskell-vim'
Plug 'elmcast/elm-vim'
Plug 'purescript-contrib/purescript-vim'
Plug 'sbdchd/neoformat'
call plug#end()

let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords

let g:elm_format_autosave = 1
let g:neoformat_enabled_purescript = ['purstidy']

augroup fmt
  autocmd!
  autocmd BufWritePre * undojoin | Neoformat
augroup END

" Fix redrawtime exceeded
set regexpengine=0 

" Disable Visual Bell
set noerrorbells visualbell t_vb=

filetype plugin indent on
syntax on
set backspace=start,eol,indent
set hidden
set noswapfile
colorscheme gruvbox
set background=dark
let mapleader = " "
set cursorline
set nu
set signcolumn=number
set encoding=utf-8
set nobackup
set nowritebackup
set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=number
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab
set smartindent
set incsearch

let mapleader = " "

nnoremap <leader>f :NERDTreeToggle<enter>
nnoremap <leader>F :NERDTreeFind<enter>
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

nmap <silent> <F1> :GFiles<enter> 
nmap <silent> <c-p> :GFiles<enter> 

source <sfile>:p:h/coc/coc-settings.vim

let g:elm_format_autosave = 1
